# Generated by Django 3.2.15 on 2022-11-14 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_title', models.CharField(max_length=100, unique=True)),
                ('race_type', models.CharField(default='race', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('horse_name', models.CharField(max_length=100, unique=True)),
                ('grade', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('going', models.CharField(max_length=50)),
                ('trainer', models.CharField(max_length=100)),
                ('jockey', models.CharField(max_length=100)),
                ('num_of_runners', models.IntegerField()),
                ('result_of_entry', models.IntegerField()),
                ('result_1', models.CharField(max_length=100)),
                ('result_2', models.CharField(max_length=100)),
                ('result_3', models.CharField(max_length=100)),
                ('note_detail', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
