# Generated by Django 3.2.15 on 2022-10-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='race_type',
            field=models.CharField(default='race', max_length=100),
        ),
    ]
